databases:
  - name: zedonk-csv-db
    plan: free
    databaseName: zedonk_csv_export
    user: zedonk_user

services:
  - type: web
    name: zedonk-csv-export
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: zedonk-csv-db
          property: connectionString
      - key: SHOPIFY_APP_URL
        value: https://zedonk-csv-export.onrender.com
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SCOPES
        value: write_products,read_orders
