# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3861d325863458c740b3c4cc4664b1cd"
name = "zedonk-csv-export"
handle = "zedonk-csv-export"
application_url = "https://loading-bacteria-above-vatican.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,read_customers"

[auth]
redirect_urls = ["https://loading-bacteria-above-vatican.trycloudflare.com/auth/callback", "https://loading-bacteria-above-vatican.trycloudflare.com/auth/shopify/callback", "https://loading-bacteria-above-vatican.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
